ekf_lio:
  ros__parameters:
    use_sim_time: false
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    world_frame: odom
    odom_frame: odom
    base_link_frame: base_link

    publish_tf: true

    # Point-LIO odom
    odom0: /aft_mapped_to_init
    odom0_config: [ true, true, false,
                    false, false, true,
                    false, false, false,
                    false, false, false,
                    false, false, false ]

    odom0_differential: false
    odom0_relative: false
