slam_toolbox:
  ros__parameters:
    use_sim_time: false
    debug_logging: true

    # Frames
    map_frame: map
    odom_frame: odom           # now a real frame in TF
    base_frame: base_link      # robot base, not the lidar

    # Topics
    scan_topic: /scan

    # SLAM mode
    mode: "mapping"
    resolution: 0.05
    map_update_interval: 0.5
    transform_publish_period: 0.05

    # Motion thresholds
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1

    # TF / timing
    tf_buffer_duration: 60.0
    throttle_scans: 1
    optimization_frequency: 0.05
